# Generated by Django 4.1 on 2022-09-03 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pho_customers',
            name='user',
        ),
    ]
