# Generated by Django 4.1 on 2022-09-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0002_remove_pho_customers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pho_customers',
            name='customer_id',
        ),
    ]
