# Generated by Django 4.1 on 2022-09-04 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pho_customer', '0003_remove_pho_customers_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pho_customers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
