# Generated by Django 4.1 on 2022-09-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0005_alter_pho_customers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pho_customers',
            name='food_preference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
