# Generated by Django 4.1 on 2022-09-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0006_pho_customers_food_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pho_customers',
            name='food_preference',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
