# Generated by Django 4.1 on 2022-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='user',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='isDelivery',
            field=models.BooleanField(default=False, verbose_name='delivery status'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='isPickup',
            field=models.BooleanField(default=False, verbose_name='pickup status'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='isVegan',
            field=models.BooleanField(default=False, verbose_name='vegan status'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='isVegetarian',
            field=models.BooleanField(default=False, verbose_name='vegetarian status'),
        ),
    ]
