# Generated by Django 4.1 on 2022-09-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_restaurant_user_alter_restaurant_isdelivery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_id',
            new_name='pho_restaurant_id',
        ),
    ]
