# Generated by Django 4.1 on 2022-09-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_restaurant_id_restaurant_pho_restaurant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
