# Generated by Django 4.1 on 2022-09-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurant_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
