# Generated by Django 4.1 on 2022-09-02 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantReview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurantreview',
            old_name='review_id',
            new_name='review',
        ),
    ]
