# Generated by Django 4.1 on 2022-09-04 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_reviews_user_reviews_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_id',
        ),
    ]
