# Generated by Django 4.1 on 2022-09-04 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0005_alter_pho_customers_user'),
        ('reviews', '0003_remove_reviews_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pho_customer.pho_customers'),
            preserve_default=False,
        ),
    ]
