# Generated by Django 4.1 on 2022-09-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
