# Generated by Django 4.1 on 2022-09-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviews_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='comment',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
