# Generated by Django 4.1 on 2022-09-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_reviews_pho_restaurant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='pho_restaurant_id',
        ),
    ]
