# Generated by Django 4.1 on 2022-09-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_rename_restaurant_id_restaurant_pho_restaurant_id'),
        ('pho_customer', '0005_alter_pho_customers_user'),
        ('reviews', '0011_remove_reviews_pho_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='pho_restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pho_customer.pho_customers'),
        ),
    ]
