# Generated by Django 4.1 on 2022-09-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_reviews_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='yelp_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
