# Generated by Django 4.1 on 2022-09-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pho_customer', '0001_initial'),
        ('customerRestaurants', '0002_rename_restaurant_id_customerrestaurant_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrestaurant',
            name='user',
        ),
        migrations.AddField(
            model_name='customerrestaurant',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pho_customer.pho_customers'),
        ),
    ]
